default: --format pretty --format html --out=report.html
iphone_sim: --tags @ios DEVICE_CONFIG='config/devices/iphone_sim.toml' SETUP_CONFIG='config/setups/two_cameras.toml'
pixel_emu: --tags @android DEVICE_CONFIG='config/devices/pixel_emu.toml' SETUP_CONFIG='config/setups/two_cameras.toml'
