default: --format pretty --format html --out=report.html
iphone_sim: DEVICE_CONFIG='config/devices/iphone_sim.toml' SETUP_CONFIG='config/setups/one_camera.toml'
pixel_emu: DEVICE_CONFIG='config/devices/pixel_emu.toml' SETUP_CONFIG='config/setups/one_camera.toml'
