---
  :caps:
    :platformName: "iOS"
    :deviceName: "iPhone 7"
    :platformVersion: "12.4"
    :noReset: true
    :app: "/Users/asusters/Desktop/protect/test-protect-poc/apps/UniFi Protect.ipa"
  :appium_lib:
    :sauce_username: false
    :sauce_access_key: false