---
  :caps:
    :platformName: "Android"
    :platformVersion: "9"
    :deviceName: "Pixel 3 API 28"
    :automationName: "UiAutomator2"
    :fullReset: true
    :app: "/Users/asusters/Desktop/protect/test-protect-poc/apps/app-playStore-release.apk"