[caps]
platformName = "Android"
platformVersion = "9"
deviceName = "Pixel 3 API 28"
automationName = "UiAutomator2"
noReset = true
app = "/Users/asusters/Desktop/protect/test-protect-cucumber/apps/app-playStore-release.apk"
appWaitActivity = "com.ubnt.sections.tos.TermsOfServiceActivity"
